# Generated by Django 3.2.20 on 2023-09-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=10, unique=True)),
                ('owner_email', models.EmailField(max_length=254, unique=True)),
                ('access_code', models.CharField(max_length=20)),
                ('client_id', models.UUIDField(unique=True)),
                ('client_secret', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('train_number', models.CharField(max_length=10)),
                ('departure_time', models.DateTimeField()),
                ('seats_available_sleeper', models.PositiveIntegerField()),
                ('seats_available_ac', models.PositiveIntegerField()),
                ('price_sleeper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_ac', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delayed_by', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
